version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 0
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 0
